### ISSUE TITLE
ja2num('三十二十') returns 50

### ISSUE THREAD

**Issue by iwamot** [twada/japanese-numerals-to-number#1]
I think this should throw Error.

**Comment by twada** [comment]
@iwamot Oh this is a bug. Thank you for reporting! I'll fix it ASAP.

**Comment by iwamot** [comment]
Thank you so much!

**Comment by twada** [comment]
Just released [japanese-numerals-to-number 1.0.2](https://github.com/twada/japanese-numerals-to-number/blob/master/CHANGELOG.md#102-2017-05-18). Thank you for reporting!

**Comment by iwamot** [comment]
Oh, thank you for your quick response!
